from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('barberias/', views.barberias, name='barberias'),
    path('barberos/', views.barberos, name='barberos'),
    path('servicios/', views.servicios, name='servicios'),
    path('contabilidad/', views.contabilidad, name='contabilidad'),
    path('contabilidad/actualizar/<int:pk>/', views.actualizar_contabilidad, name='actualizar_contabilidad'),
    path('contabilidad/eliminar/<int:pk>/', views.eliminar_contabilidad, name='eliminar_contabilidad'),
    path('promociones/', views.promociones, name='promociones'),
    path('profile/', views.profile, name='profile'),
    path('profile/change-password/', views.change_password, name='change_password'),
    path('catalogo-cortes/', views.catalogo_cortes, name='catalogo_cortes'),
    path('catalogo-cortes/eliminar/<int:pk>/', views.eliminar_corte, name='eliminar_corte'),
    path('citas/', views.citas, name='citas'),
    path('citas/eliminar/<int:pk>/', views.eliminar_cita, name='eliminar_cita'),
    path('promociones/', views.promociones, name='promociones'),
    path('promociones/agregar/', views.agregar_promocion, name='agregar_promocion'),
    path('promociones/editar/<int:pk>/', views.editar_promocion, name='editar_promocion'),
    path('promociones/eliminar/<int:pk>/', views.eliminar_promocion, name='eliminar_promocion'),
    path('barberias/', views.barberias, name='barberias'),
    path('barberias/agregar/', views.agregar_barberia, name='agregar_barberia'),
    path('barberias/editar/<int:pk>/', views.editar_barberia, name='editar_barberia'),
    path('barberias/eliminar/<int:pk>/', views.eliminar_barberia, name='eliminar_barberia'),
    path('servicios/', views.servicios, name='servicios'),
    path('servicios/agregar/', views.agregar_servicio, name='agregar_servicio'),
    path('servicios/editar/<int:pk>/', views.editar_servicio, name='editar_servicio'),
    path('servicios/eliminar/<int:pk>/', views.eliminar_servicio, name='eliminar_servicio'),
    path('barberos/', views.barberos, name='barberos'),
    path('barberos/agregar/', views.agregar_barbero, name='agregar_barbero'),
    path('barberos/editar/<int:pk>/', views.editar_barbero, name='editar_barbero'),
    path('barberos/eliminar/<int:pk>/', views.eliminar_barbero, name='eliminar_barbero'),
]