# Generated by Django 5.1.1 on 2024-10-03 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('descripcion', models.TextField()),
                ('imagen_logo', models.ImageField(blank=True, null=True, upload_to='barberias_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gastos', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion_estimada', models.DurationField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='barbershop',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='user',
        ),
        migrations.RemoveField(
            model_name='haircutphoto',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='review',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='haircutphoto',
            name='haircut_style',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_profesional', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('anos_experiencia', models.IntegerField()),
                ('especialidad', models.CharField(max_length=100)),
                ('disponibilidad', models.TextField()),
                ('nombre_completo', models.CharField(max_length=255)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='barberos_perfiles/')),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barberia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCortes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estilo', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(upload_to='catalogo_cortes/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='catalogo_cortes/')),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbero')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbero')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=7)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/')),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barberia')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Barbershop',
        ),
        migrations.DeleteModel(
            name='Barber',
        ),
        migrations.DeleteModel(
            name='HaircutPhoto',
        ),
        migrations.DeleteModel(
            name='HaircutStyle',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
