# Generated by Django 5.1.1 on 2024-10-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0007_remove_catalogocortes_descripcion_cita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogocortes',
            old_name='imagen',
            new_name='imagen1',
        ),
        migrations.AddField(
            model_name='barbero',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='barberos_perfiles/'),
        ),
        migrations.AddField(
            model_name='barbero',
            name='nombre_completo',
            field=models.CharField(default='Nombre Completo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogocortes',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo_cortes/'),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='gastos',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='ingresos',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='promociones',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
